project:
  type: website

website:
  title: "Caroline R Wensel"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - example-analysis.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

